name: Allure Report

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  allure-report:
    runs-on: ubuntu-latest
    # Se ejecuta siempre, sin importar si las pruebas pasan o fallan
    if: always()
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download Allure results
      uses: actions/download-artifact@v4
      with:
        name: allure-results
        path: allure-results/
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Allure
      run: |
        npm install -g allure-commandline
    
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report 